# Use root/example as user/password credentials
version: '3.1'

services:
  mongodb:
    image: mongo
    restart: always
    volumes:
      - data:/data/db
    env_file:
      - ./.env
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${ROOT_PASSWORD}

volumes:
  data: